# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "Anthony's Random Writings"
description: > # this means to ignore newlines until "email:"
  Everything from development to music

email: neueanthony@me.com

#blog logo
logo: "/anth/assets/images/anth.jpg"

# blog cover
cover: "/anth/assets/images/home-bg.jpg"

name: 'Anthony Castelli'
author: 'Anthony Castelli'
author_image: "/anth/assets/images/anth.jpg"

paginate:	5

url: "http://anthonycastelli.github.io" # the base hostname & protocol for your site
baseurl: "/anth"

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/anthness
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/anthonycastelli
    desc:	Follow me on GitHub
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
